sudo: required
services:
  - docker

before_install:
  - docker build -t cheonu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cheonu/react-test npm test

after_success:
  - docker build -t cheonu/multi-client ./client
  - docker build -t cheonu/multi-nginx ./nginx
  - docker build -t cheonu/multi-server ./nginx
  - docker build -t cheonu/multi-worker ./worker

  #log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push cheonu/multi-client
  - docker push cheonu/multi-nginx
  - docker push cheonu/multi-server
  - docker push cheonu/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker 
  env: Multidocker1-env
  bucketname: elasticbeanstalk-us-east-2-898635122151
  bucketpath: docker-multi 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY    