sudo: required
services:
  - docker

before_install:
  - docker build -t cheonu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run cheonu/react-test npm test -- --coverage

after_success:
  - docker build -t cheonu/multi-client ./client
  - docker build -t cheonu/multi-nginx ./nginx
  - docker build -t cheonu/multi-server ./nginx
  - docker build -t cheonu/multi-worker ./worker

  #log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push cheonu/multi-client
  - docker push cheonu/multi-nginx
  - docker push cheonu/multi-server
  - docker push cheonu/multi-worker